name: CI Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t ci-demo .

    - name: Run CI inside container
      run: |
        docker run \
          -v ${{ github.workspace }}:/app \
          ci-demo
   
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: reports
   
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Pytest Tests
        path: reports/test-report.xml
        reporter: java-junit
   